### PR TITLE
Cleaned up version of KR 3 CR urdf model

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This is for ROS Answers [Unable to move links withing URDF file](http://answers.ros.org/question/221675/unable-to-move-links-withing-urdf-file/).

Basically, I haven't even tried to diagnose the original URDF, as there were too many issues with it, probably due to the conversion done by `collada_to_urdf`. I also suspect a discrepancy between the joint transforms in the original urdf and the meshes that were converted separately.

In the end, I:
- converted everything to a xacro macro (added top-level xacro as well)
- made naming consistent with ROS standards (`base_link`, etc)
- cleaned up all urdf joint transforms: based on data from a KR 3 CR [datasheet](http://www.gspnexus.com/schedetecniche/KR3CRv1.pdf)
- removed collada->urdf conversion artefacts (unnecessary xml ns decls, etc)
- changed origins of all meshes to be relative to the joint zero, instead of to the global robot zero
- scaled meshes (ROS uses meters, meshes were in millimeters)
- fixed orientations of all meshes: X forward, Y to the left, Z up (ROS standard)
- created collision quality meshes (convex hulls)
- split out visual and collision quality meshes of KR 3 CR into separate directories

Note:
- origins of all `intertial` elements has been reset to zeros as I don't know what the real values should be
- masses, origins and values for `inertia` elements are incorrect
- `effort` limits of all joints have suspicious values (if unknown, just leave them at zero, unless you need to simulate with Gazebo obviously)
- `dynamics` element attributes seem to have standard values

I also added two convenience launch files to easily load and display the model in RViz (`roslaunch urdf_collection test_kr3cr.launch`).

Most of this is based on the [Create a URDF for an Industrial Robot](http://wiki.ros.org/Industrial/Tutorials/Create%20a%20URDF%20for%20an%20Industrial%20Robot) and [Working with ROS-Industrial Robot Support Packages](http://wiki.ros.org/Industrial/Tutorials/WorkingWithRosIndustrialRobotSupportPackages) tutorials from ROS-Industrial.

I also created a test MoveIt configuration to verify the model and could successfully plan for it.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Btw, I'm one of the maintainers of the ROS-Industrial [ros-industrial/kuka_experimental](https://github.com/ros-industrial/kuka_experimental) repository. Would you be interested in submitting this model for inclusion in that repository? It would require some additional changes, but should not take too long.

**Comment by gavanderhoorn** [comment]
Also: I haven't touched any of the original files (urdf, meshes), although they are not longer needed. Whether you want to remove them is up to you though.

**Comment by aleksandaratanasov** [comment]
Definitely fine by me. There might be one issue though - the detailed internal statistics (not the ones that are in the datasheet of the robot which can be found online somewhere) are available only in the manuals of the robots. I have no idea what the legal issues are. If you have some contacts you might want to ask. I have Michael Haag (leads the development department at KUKA and also teaches robotics at my university in B.S. Computer Science) and Heinz Wörn (top figure at KUKA before he moved to KIT IPR, where I'm currently working at). I'm going to work on Monday and will ask. _If no detailed internal stats are required then there is no problem in adding the model to the ROS repo_. I remember that when I was working at Fraunhofer IPA (Stuttgart) I created a model for the Reis RV40 using OpenRAVE (you will still be able to find my posts in the mailinglist of OpenRAVE :D) but I wasn't allowed to post content online especially with the real stats that were not available in the datasheet.

I also wanted to actually start from scratch but due to time limitations I decided to go for the conversion tool provided by ROS. Do you know whether there is an opened issue about the weird results `collada_to_urdf`produces?

Thanks you so much for your help! I will contact you next week with an update if you want to.

**Comment by gavanderhoorn** [comment]
If by _detailed statistics_ you mean the actual inertias, masses etc then I understand. We don't need those (or at least, not in the publicly available models). It would however be nice to have as accurate models as possible, so if we can release them, that would be preferred, obviously.

as to your issue with `collada_to_urdf`: as I wrote, I only have some ideas, I don't know for certain. But I think the convoluted urdf in combination with the 'messy' meshes resulted in some strange things. You can always open a ticket if you feel you can reproduce the issues (with some mwe).

**Comment by aleksandaratanasov** [comment]
I understand. Yes, I meant the actual data that is not publicly available but only between KUKA and its customers. As for the accurate model - I used the Collada file that Rosen Diankov created for me though I don't know where he got the model himself. At first I actually wanted to do the conversion from let's say STEP or IGES to URDF on my own but I found it extremely difficult to find any CAD model of this robot in particular. The STEP file I found is _not_ from KUKA's official website. In fact the KR3 CR is only mentioned in a bunch of text snippets there and in the download section there is not a single trace of any CAD files for it. I can of course look up the documentation myself and try to change the 3D data but it will take me some time because of other projects I'm currently working on. This however falls into the same legal trap as the detailed statistics we have discussed due to the fact that the models that KUKA provides on their website are inaccurate to say the least. I personally have sent two mail message with correction for one of their CAD models that had some weird tiny vertices sticking out at a couple of places that were causing constant state of collision in OpenRAVE (that's how I found these problems in the first place :D). I can only assume that the technical documentation shipped with the robot is accurate enough though I doubt that KUKA will distribute their designs in such a way.

**Comment by gavanderhoorn** [comment]
> As for the accurate model - I used the Collada file that Rosen Diankov created for me though I don't know where he got the model himself. At first I actually wanted to do the conversion from let's say STEP or IGES to URDF on my own but I found it extremely difficult to find any CAD model of this robot in particular. The STEP file I found is not from KUKA's official website. In fact the KR3 CR is only mentioned in a bunch of text snippets there and in the download section there is not a single trace of any CAD files for it.

I found it relatively easily at their site by going to [KUKA - Downloads - CAD](http://www.kuka-robotics.com/en/downloads/search/?type=current&sc_META_02=CAD), then selecting _Archive_ under _Filter options_, expanding _Product designation_ and scrolling down to _KR 3 CR (5)_. Direct linking to that overview page is impossible, but the STEP fi can be found [here](http://www.kuka-robotics.com/res/sps/8ba89f50-3ccd-4361-9b9a-60bdd0662ac6_kr3_STEP.zip).

As to the accuracy of those models: I've never really found too many issues with them, but that could be just fortunate sampling. 

> I can of course look up the documentation myself and try to change the 3D data but it will take me some time because of other projects I'm currently working on. 

What would you want to change? I was just trying to say that if we are allowed to include things like inertia values, then we should. If not, too bad, but then we have at least the base model, and users can add those values for themselves.

**Comment by aleksandaratanasov** [comment]
Ah, you are a magician. :D I guess I overlooked it (along with Google LOL).

As for the changes - since I had bad experience with some of their models I presume it would be nice if I can check the model for some bad vertices or inaccuracies in the measurements. On Monday I will ask about the stats such as inertia, mass etc. and provide those as soon as I can if possible at all.

**Comment by gavanderhoorn** [comment]
> I struggled with GitHub to find out a way of communicating with you

You can get my work email address from any commit in any of the ROS-Industrial pkgs or those on my work github account. Alternatively look at messages on the [ros-industrial mailing list](https://groups.google.com/forum/#!forum/swri-ros-pkg-dev).

> In addition can you please tell me what I can do to improve the model so that it meets some higher quality standards and - if you want to - include it in the ROS repository?

Yes, of course. We always appreciate contributions, especially robot models as it saves other users a lot of work.

It's probably easiest if you contact me via email. I'll gladly help you.

**Pull request merged**
